name: agri_connect
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.9
  firebase_storage: ^11.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.5.0
  image_picker: ^1.0.4
  provider: ^6.1.1

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
